#In this example we assume that 10Gi volume named named uber-disk is already created
#in the google cloud, also called a GCE persistent disk.
# This only creates the PV.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteOnce
  #The PVC will use storageClassName as a way to point to this PV much like a label
  storageClassName: test
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: uber-disk