# Note that we are only using a single Pod to keep things simple. 
# Pods deployed like this are usually called Singletons and are not recommended
# for production because they do not provide self healing or high availability.
# For production, look at Stateful sets or Deployments.
apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  # First we define a volume and name it data.
  # This volume will leverage on the previously created
  # PVC called pvc1.
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc1
  # then we mount this volume on the pod by refering to it
  # via its name "data"
  containers:
  - name: testpod
    image: ubuntu
    tty: true
    stdin: true
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: /data
      name: data