apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: todo
      zone: prod
      version: v1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: todo
        zone: prod
        version: v1
    spec:
      containers:
      - name: todo-pod
        image: trashpandarecon/todo_list:1.0
        ports:
        - containerPort: 3000