# This are examples of all 3 types of ConfigMap injection methods,
# Env, startup, and ConfigMap volumes
# Note that all these methods work for any pod controller as well
apiVersion: v1
kind: ConfigMap
metadata:
  name: multimap
data:
  # the pipe | character after the key tells Kubernetes that
  # everything following the pipe is to be treated as a single
  # literal value. You can even write entire scripts here.
  test.conf: | 
    env = mongodb
    endpoint = 0.0.0.0:30123
    char = utf8
    logging-enabled = true
    log-size = 1Gi
  given: Hatzu
  family: Rei
---
# a short Opaque Secret example
# lets say our application uses the following config.yaml file.
# apiUrl: "https://my.api.com/api/v1"
# username: "<user>"
# password: "<password>"
# This will be the coresponding Secret.
apiVersion: v1
kind: Secret
metadata:
  name: secretmap
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://my.api.com/api/v1"
    username: firstuser
    password: notpassword
---
# examples of how to use ConfigMaps in a Pod and inserts via startup and env
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-startup
spec:
  # the default restartPolicy is Always, this can lead to single use Pods
  # constantly restarting themselves and running the same command over and over again
  restartPolicy: OnFailure
  containers:
    - name: ubuntu
      image: ubuntu
      command: [ "/bin/sh", "-c", "echo First name $(FIRSTNAME) last name $(LASTNAME)" ]
      env:
          - name: FIRSTNAME
            valueFrom:
              configMapKeyRef:
                name: multimap
                key: given
          - name: LASTNAME
            valueFrom:
              configMapKeyRef:
                name: multimap
                key: family
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
---          
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-vol
spec:
# declaring a ConfigMap volume and Secret volume
  volumes:
    - name: secretvolmap
      secret:
          secretName: secretmap
    - name: volmap
      configMap:
          name: multimap
  containers:
    - name: ubuntu
      image: ubuntu
      tty: true
      stdin: true
      # We mount both volumes into the container here
      volumeMounts:
        - name: volmap
          mountPath: /etc/config
        - name: secretvolmap
          mountPath: /etc/sconfig
          readOnly: true
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"

