apiVersion: v1
kind: Deployment
metadata:
  name: visualizer-backend-devpod
  labels:
    name: visualizer-backend-devpod
spec:
  containers:
  - name: visualizer-backend-devpod
    image: trashpandarecon/sde-visualizer-backend:1.0.0
    tty: true
    stdin: true
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
    ports:
      - containerPort: 3456
---
kind: Service
apiVersion: v1
metadata:
  name:  visualizer-backend-svc
spec:
  selector:
    name: visualizer-backend-devpod
  type: NodePort
  ports:
  - name:  visualizer-backend
    protocol: TCP
    port:  3456
    targetPort:  3456
    nodePort: 30002