apiVersion: v1
kind: Pod
metadata:
  name: visualizer-frontend-devpod
  labels:
    name: visualizer-frontend-devpod
spec:
  containers:
    - name: visualizer-frontend-devpod
      image: trashpandarecon/sde-visualizer-frontend:1.0.0
      tty: true
      stdin: true
      resources:
        limits:
          memory: '1Gi'
          cpu: '1000m'
      ports:
        - containerPort: 3000
    
---
kind: Service
apiVersion: v1
metadata:
  name: visualizer-svc
spec:
  selector:
    name: visualizer-frontend-devpod
  type: NodePort
  ports:
    - name: name-of-the-port
      port: 3000
      targetPort: 3000
      nodePort: 30001
